version: '3.8'


services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - backend
      - frontend
      - jquery-app
    networks:
      - dev


  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      - SECRET_KEY=${SECRET_KEY}
    networks:
      - dev


  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    networks:
      - dev

  jquery-app:
    build:
      context: ./jquery
      dockerfile: Dockerfile
    ports:
      - "4000:4000"  # Прокси на порт 4000
    networks:
      - dev

networks:
  dev:
    driver: bridge